// export const API_ENDPOINT = "http://192.168.1.46:4000"
// export const SOCKET_ENDPOINT = "http://192.168.1.46:4050"
export const API_ENDPOINT = "http://68.183.178.189:4000"
export const SOCKET_ENDPOINT = "http://68.183.178.189:4050"

export const API_REGISTER = API_ENDPOINT + "/api/v1/user/register"
export const API_LOGIN = API_ENDPOINT + "/api/v1/user/login"
export const API_LOGOUT = API_ENDPOINT + "/api/v1/user/logout"
export const API_GET_NOTIFICATION_RECORD = API_ENDPOINT + "/api/v1/user/getrecord"
export const API_GET_TRIPDATA = API_ENDPOINT + "/api/v1/gettripdata"
export const API_GET_ALL_TRIPS = API_ENDPOINT + "/api/v1/getalltrips"