// export const API = "http://localhost:4000"
export const API = "https://drowsy-project.firebaseapp.com"
export const API_REGISTER = API + "/api/v1/user/register"
export const API_LOGIN = API + "/api/v1/user/login"
export const API_LOGOUT = API + "/api/v1/user/logout"
export const API_GET_NOTIFICATION_RECORD = API + "/api/v1/user/getrecord"
export const API_GET_TRIPDATA = API+"/api/v1/gettripdata"
export const API_GET_ALL_TRIPS = API+"/api/v1/getalltrips"